"""
udp_report.py
-------------
Builds the post-migration validation report for one SAP PowerDesigner -> erwin
UDP migration, and writes it as:

    output_excel_reports/<model_name>_UDP_Migration_Report.xlsx

The report is assembled from what actually happened during the run, not from
what was supposed to happen:

    * udp_schema.json            - the UDP definitions that were requested
    * property_manifest.json     - the source values extracted from PowerDesigner
    * injection_results.json     - what erwin actually accepted, written by
                                   erwin_load.py, including the value read back
                                   out of erwin after each write
    * classification_<model>.json / baseline/*.json - source-model facts

If injection_results.json is missing (for example the report is regenerated by
hand without re-running the COM injection) every value is reported as
"Not Verified" rather than being silently counted as a success.

Sheets: Summary | UDP Definition | Value Reconciliation | Exceptions

Usage:
  python udp_report.py --model_name "MODEL" --manifest ... --schema ...
                       --results ... --outdir output_excel_reports
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

try:
    from openpyxl import Workbook
    from openpyxl.cell.cell import ILLEGAL_CHARACTERS_RE
    from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
    from openpyxl.utils import get_column_letter
except ImportError:
    print("Error: The 'openpyxl' library is not installed. Please run 'pip install openpyxl'.")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Presentation constants
# ---------------------------------------------------------------------------
FONT = "Arial"
HDR_FILL = PatternFill("solid", fgColor="1F3864")
HDR_FONT = Font(name=FONT, size=10, bold=True, color="FFFFFF")
TITLE_FONT = Font(name=FONT, size=14, bold=True, color="1F3864")
SECTION_FONT = Font(name=FONT, size=11, bold=True, color="1F3864")
LABEL_FONT = Font(name=FONT, size=10, bold=True)
SECTION_FILL = PatternFill("solid", fgColor="D9E2F3")
THIN = Side(style="thin", color="B4C6E7")
BOX = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)
WRAP = Alignment(vertical="top", wrap_text=True)
TOP = Alignment(vertical="top")

# Status vocabulary - shared with erwin_load.py and used by the Summary formulas.
ST_VERIFIED = "Applied - Verified"
ST_ALTERED = "Applied - Value Altered"
ST_UNVERIFIED = "Applied - Not Verified"
ST_NO_ENTITY = "Skipped - Entity Not Found In erwin"
ST_REJECTED = "Skipped - Property Rejected By erwin"
ST_NOT_RUN = "Not Verified - No Injection Result"

MAX_CELL = 2000  # trim pathological PowerDesigner blobs so Excel stays usable


def blank_safe(value):
    """Cleaned value, or a truly empty cell so COUNTBLANK/filters behave."""
    text = clean(value)
    return text if text else None


def clean(value) -> str:
    """Make any source value safe to write into a cell."""
    if value is None:
        return ""
    text = str(value)
    text = ILLEGAL_CHARACTERS_RE.sub("", text).replace("\x00", "")
    if len(text) > MAX_CELL:
        text = text[:MAX_CELL] + " ...[truncated]"
    return text


def read_json(path: Path, default=None):
    """Read a JSON file, returning `default` if it is absent or unreadable."""
    try:
        if path and Path(path).exists():
            return json.loads(Path(path).read_text(encoding="utf-8", errors="replace"))
    except Exception as exc:
        print(f"       Notice: could not read {path} ({exc}).")
    return default


def header_row(ws, headers, row=1):
    """Write a styled header row and switch on filtering + frozen panes."""
    for col, text in enumerate(headers, start=1):
        cell = ws.cell(row=row, column=col, value=text)
        cell.font = HDR_FONT
        cell.fill = HDR_FILL
        cell.border = BOX
        cell.alignment = Alignment(vertical="center", wrap_text=True)
    ws.row_dimensions[row].height = 28
    # Use a string reference - ws.cell() would materialise the row and leave a
    # blank line above the data.
    ws.freeze_panes = f"A{row + 1}"
    ws.auto_filter.ref = f"A{row}:{get_column_letter(len(headers))}{row}"


def set_widths(ws, widths):
    for idx, width in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(idx)].width = width


# ---------------------------------------------------------------------------
# Reconciliation - join the source manifest to what erwin actually accepted
# ---------------------------------------------------------------------------
def build_reconciliation(manifest: list, results: dict | None) -> list[dict]:
    """
    One row per source property value, carrying the outcome erwin reported.

    The join key is (entity_name, udp, source_path) plus an occurrence counter,
    which keeps duplicate property paths on the same entity distinct.
    """
    outcomes = {}
    if results:
        for item in results.get("values", []):
            key = (
                str(item.get("entity_name", "")).lower(),
                str(item.get("udp", "")),
                str(item.get("source_path", "")),
                item.get("occurrence", 0),
            )
            outcomes[key] = item

    seen = {}
    rows = []
    for src in manifest:
        entity = str(src.get("entity_name", ""))
        udp = str(src.get("udp", ""))
        path = str(src.get("source_path", ""))
        base_key = (entity.lower(), udp, path)
        occurrence = seen.get(base_key, 0)
        seen[base_key] = occurrence + 1

        outcome = outcomes.get(base_key + (occurrence,))
        source_value = src.get("value", "")

        if outcome is None:
            status = ST_NOT_RUN
            target_value = ""
            applied_to = "Model Root" if not entity else "Entity"
            note = "No injection result recorded for this value."
        else:
            status = outcome.get("status", ST_NOT_RUN)
            target_value = outcome.get("target_value", "")
            applied_to = outcome.get("applied_to", "")
            note = outcome.get("note", "")

        if status == ST_VERIFIED:
            match = "Match"
        elif status == ST_ALTERED:
            match = "Mismatch"
        elif status == ST_UNVERIFIED:
            match = "Unverified"
        else:
            match = "Not Applied"

        rows.append({
            "entity_name": entity,
            "pd_object_id": str(src.get("pd_object_id", "")),
            "udp": udp,
            "source_path": path,
            "source_value": source_value,
            "target_value": target_value,
            "applied_to": applied_to,
            "status": status,
            "match": match,
            "note": note,
        })
    return rows


# ---------------------------------------------------------------------------
# Sheet 3: Value Reconciliation
# ---------------------------------------------------------------------------
def write_reconciliation(ws, rows):
    header_row(ws, [
        "Entity Name", "PD Object ID", "UDP", "Source Path",
        "Source Value (PowerDesigner)", "Target Value (erwin)",
        "Applied To", "Status", "Match", "Notes",
    ])
    set_widths(ws, [34, 30, 28, 30, 42, 42, 12, 30, 13, 44])
    for row in rows:
        ws.append([
            blank_safe(row["entity_name"]), blank_safe(row["pd_object_id"]),
            blank_safe(row["udp"]), blank_safe(row["source_path"]),
            blank_safe(row["source_value"]), blank_safe(row["target_value"]),
            blank_safe(row["applied_to"]), row["status"], row["match"],
            blank_safe(row["note"]),
        ])


# ---------------------------------------------------------------------------
# Sheet 2: UDP Definition
# ---------------------------------------------------------------------------
def write_definitions(ws, schema, results, recon_rows):
    header_row(ws, [
        "UDP Name", "Inferred Type", "Length", "Value List (Observed)", "Source Path",
        "Source Coverage", "Distinct Observed", "List Source", "erwin Owner Types",
        "erwin Dictionary Action", "Values Expected", "Values Applied", "Values Verified",
        "Definition Status",
    ])
    set_widths(ws, [30, 13, 9, 44, 30, 14, 16, 38, 16, 30, 15, 15, 15, 34])

    # Collapse the per-owner dictionary outcomes onto their UDP.
    actions: dict[str, list] = {}
    if results:
        for entry in results.get("dictionary", []):
            actions.setdefault(str(entry.get("udp", "")), []).append(entry)

    used_udps = {row["udp"] for row in recon_rows}

    for prop in schema:
        name = str(prop.get("udp", ""))
        entries = actions.get(name, [])
        if entries:
            owners = ", ".join(sorted({str(e.get("owner", "")) for e in entries}))
            action = "; ".join(
                f"{e.get('action', 'unknown').title()} ({e.get('owner', '')})"
                + (f" - {e.get('error')}" if e.get("error") else "")
                for e in entries
            )
        else:
            owners = "Entity, Model"
            action = "Not Recorded" if not results else "Not Created"

        value_list = prop.get("value_list") or []
        row_no = ws.max_row + 1
        expected = f"=COUNTIF('Value Reconciliation'!$C:$C,$A{row_no})"
        applied = (f"=COUNTIFS('Value Reconciliation'!$C:$C,$A{row_no},"
                   f"'Value Reconciliation'!$H:$H,\"Applied*\")")
        verified = (f"=COUNTIFS('Value Reconciliation'!$C:$C,$A{row_no},"
                    f"'Value Reconciliation'!$I:$I,\"Match\")")

        if not entries and results:
            status = "NOT CREATED - definition missing in erwin dictionary"
        elif any(e.get("action") == "failed" for e in entries):
            status = "FAILED - erwin rejected the definition"
        elif name not in used_udps:
            status = "Defined - no source values to migrate"
        elif value_list:
            status = "Defined as List - observed values only, confirm against BIM-core.xem"
        else:
            status = "Defined"

        ws.append([
            clean(name), clean(prop.get("type", "")), prop.get("length") or "",
            clean(" | ".join(str(v) for v in value_list)), clean(prop.get("source_path", "")),
            clean(prop.get("coverage", "")), prop.get("distinct_observed", ""),
            clean(prop.get("list_source", "")), owners, clean(action),
            expected, applied, verified, status,
        ])
        for col in range(1, 15):
            ws.cell(row=row_no, column=col).alignment = WRAP


# ---------------------------------------------------------------------------
# Sheet 4: Exceptions
# ---------------------------------------------------------------------------
def write_exceptions(ws, recon_rows, schema, results, classification, entities):
    header_row(ws, [
        "Severity", "Category", "Entity", "UDP", "Detail", "Recommended Action",
    ])
    set_widths(ws, [12, 30, 34, 28, 62, 54])

    rows = []

    # 1. Definitions erwin refused.
    for entry in (results or {}).get("dictionary", []):
        if entry.get("action") == "failed":
            rows.append(["High", "UDP definition failed", "", entry.get("udp", ""),
                         clean(entry.get("error", "erwin rejected the definition."))
                         or "erwin rejected the definition.",
                         "Re-run injection with the erwin UI open, then confirm the UDP "
                         "appears under Model > UDPs."])

    # 2. Values erwin did not accept, or accepted then changed.
    for row in recon_rows:
        if row["status"] == ST_NO_ENTITY:
            rows.append(["High", "Entity not found in erwin", row["entity_name"], row["udp"],
                         "The source entity has no match in the target .erwin model, so this "
                         "value was not migrated.",
                         "Confirm the entity survived the erwin bridge import, or that the "
                         "entity name matches between the two models."])
        elif row["status"] == ST_REJECTED:
            rows.append(["High", "Property rejected by erwin", row["entity_name"], row["udp"],
                         clean(row["note"]) or "erwin did not accept any known property "
                                               "name format for this UDP.",
                         "Check the UDP exists in the erwin dictionary for this owner type "
                         "(Entity vs Model)."])
        elif row["status"] == ST_ALTERED:
            rows.append(["High", "Value altered on write", row["entity_name"], row["udp"],
                         f"Source: {clean(row['source_value'])[:180]} | "
                         f"erwin returned: {clean(row['target_value'])[:180]}",
                         "Usually a List UDP rejecting a value outside its permitted list. "
                         "Widen the list or correct the source value."])
        elif row["status"] == ST_NOT_RUN:
            rows.append(["Medium", "Not verified", row["entity_name"], row["udp"],
                         "No injection result was recorded for this value.",
                         "Re-run batch_run.py so the report is built from a live "
                         "injection result."])

    # 3. Source-side data quality that limits what can be reconciled later.
    for row in recon_rows:
        if row["udp"] == "PD_ObjectID" and not str(row["source_value"]).strip():
            rows.append(["Medium", "Missing PowerDesigner ObjectID", row["entity_name"], "PD_ObjectID",
                         "The source entity carries no ObjectID, so there is no permanent "
                         "join key for a future re-run or reconciliation.",
                         "Confirm with the Shell data architect whether the PD extract "
                         "should be re-taken with ObjectIDs included."])
        elif not str(row["source_value"]).strip():
            rows.append(["Low", "Empty source value", row["entity_name"], row["udp"],
                         "The property exists on the source entity but holds no value.",
                         "No action if the property is genuinely blank in PowerDesigner."])

    for entity in entities or []:
        if not str(entity.get("name", "")).strip():
            rows.append(["Medium", "Unnamed source entity", clean(entity.get("code", "")), "",
                         "The source entity has no name, so its values are written against "
                         "the model root instead of an entity.",
                         "Name the entity in PowerDesigner and re-extract."])

    # 4. Inferred value lists are observed, not authoritative.
    for prop in schema:
        if prop.get("value_list"):
            rows.append(["Low", "Inferred value list", "", prop.get("udp", ""),
                         "The permitted values were inferred from observed data, not from "
                         "BIM-core.xem. Observed is not the same as permitted.",
                         "Confirm the list against BIM-core.xem before sign-off."])

    # 5. Constructs the SOW says the bridge cannot carry.
    for item in (classification or {}).get("non_equivalence_register", []):
        disposition = str(item.get("disposition", ""))
        if "NOT RECOVERABLE" in disposition.upper() or "OUT OF SCOPE" in disposition.upper():
            rows.append(["Informational", "Not carried by the erwin bridge", "",
                         clean(item.get("construct", "")),
                         f"{clean(item.get('volume', ''))} - {clean(item.get('bridge', ''))}",
                         clean(disposition)])

    order = {"High": 0, "Medium": 1, "Low": 2, "Informational": 3}
    rows.sort(key=lambda r: (order.get(r[0], 9), r[1], str(r[2])))

    # A category with thousands of identical rows buries the ones that matter.
    # Keep the first CAP as examples and summarise the remainder; the full
    # detail is still on the Value Reconciliation sheet.
    cap = 100
    capped, counts = [], {}
    for row in rows:
        key = (row[0], row[1])
        counts[key] = counts.get(key, 0) + 1
        if counts[key] <= cap:
            capped.append(row)
    for (severity, category), total in counts.items():
        if total > cap:
            capped.append([severity, category, "", "",
                           f"{total} rows in this category; the first {cap} are listed above.",
                           "Filter the Value Reconciliation sheet for the full list."])
    rows = capped
    rows.sort(key=lambda r: (order.get(r[0], 9), r[1], str(r[2])))

    if not rows:
        rows = [["Informational", "No exceptions", "", "",
                 "Every source value was applied and verified against erwin.", "None."]]

    for row in rows:
        ws.append([blank_safe(c) for c in row])
        for col in range(1, 7):
            ws.cell(row=ws.max_row, column=col).alignment = WRAP
    return len(rows)


# ---------------------------------------------------------------------------
# Sheet 1: Summary
# ---------------------------------------------------------------------------
def write_summary(ws, ctx):
    set_widths(ws, [42, 26, 76])
    ws["A1"] = "UDP Migration Report - SAP PowerDesigner to erwin Data Modeler"
    ws["A1"].font = TITLE_FONT
    ws.merge_cells("A1:C1")
    ws.row_dimensions[1].height = 22

    def section(title):
        row = ws.max_row + 2
        for col in range(1, 4):
            cell = ws.cell(row=row, column=col, value=title if col == 1 else "")
            cell.fill = SECTION_FILL
            cell.font = SECTION_FONT if col == 1 else Font(name=FONT, size=10)
            cell.border = BOX
        return row

    def line(label, value, note="", bold_value=False):
        row = ws.max_row + 1
        ws.cell(row=row, column=1, value=label).font = LABEL_FONT
        cell = ws.cell(row=row, column=2, value=value)
        cell.font = Font(name=FONT, size=10, bold=bold_value)
        cell.alignment = TOP
        ws.cell(row=row, column=3, value=note).alignment = WRAP
        return row

    recon = "'Value Reconciliation'"
    total = f"=MAX(0,COUNTA({recon}!$C:$C)-1)"

    section("Run Information")
    line("Report generated", ctx["generated"])
    line("Model name", ctx["model_name"])
    line("Source SAP model", ctx["sap_model"], "PowerDesigner model read for this run.")
    line("Target erwin model", ctx["erwin_out"], "File the UDPs were written into.")
    line("PowerDesigner version", ctx["pd_version"])
    line("Repository extraction id", ctx["extraction_id"],
         "Proves which point-in-time extract this migration came from.")
    line("Injection executed", ctx["injection_state"],
         "" if ctx["results"] else "Values below are reported as Not Verified because no "
                                   "injection result file was available.")
    line("erwin session", ctx["session_note"])

    section("Source Model (SAP PowerDesigner)")
    line("Complexity band", f"{ctx['band']} - {ctx['band_label']}",
         "From sow_classify.py, per the SOW Complexity Classification Spectrum.")
    line("SOW automation range", ctx["automation_range"])
    line("Entities in source model", ctx["entities_source"])
    line("Attributes in source model", ctx["attributes_source"])
    line("Extension properties found", ctx["ext_properties"])
    line("Extension values found", ctx["ext_values"])

    section("UDP Definitions")
    defs = "'UDP Definition'"
    line("UDP definitions requested", f"=MAX(0,COUNTA({defs}!$A:$A)-1)",
         "Each UDP is defined twice in erwin, once for the Entity owner and "
         "once for the Model owner.")
    line("Created in erwin dictionary", f'=COUNTIF({defs}!$J:$J,"Created*")',
         "Counted per UDP, not per owner.")
    line("Updated in erwin dictionary", f'=COUNTIF({defs}!$J:$J,"Updated*")',
         "UDPs that already existed in the target model and were re-pointed.")
    line("Definition failures", f'=COUNTIF({defs}!$N:$N,"FAILED*")',
         "A UDP counts as failed if erwin rejected either owner definition. "
         "See the Exceptions sheet for the reason.")

    section("Value Reconciliation")
    line("Entities matched in erwin", ctx["entities_target"],
         "Entities the injector found in the target .erwin model.")
    total_row = line("Source values to migrate", total)
    applied_row = line("Applied to erwin", f'=COUNTIF({recon}!$H:$H,"Applied*")')
    verified_row = line("Applied and verified (read back)",
                        f'=COUNTIF({recon}!$I:$I,"Match")',
                        "Value was written, then read back out of erwin and compared.")
    altered_row = line("Applied but value altered", f'=COUNTIF({recon}!$I:$I,"Mismatch")')
    skipped_row = line("Not applied", f'=COUNTIF({recon}!$H:$H,"Skipped*")')
    last = ctx["recon_last_row"]
    line("Blank source values",
         f'=COUNTBLANK({recon}!$E$2:$E${last})' if last >= 2 else 0,
         "Properties present in PowerDesigner but holding no value.")

    section("Result")
    rate = line("Application rate",
                f"=IF(B{total_row}=0,0,B{applied_row}/B{total_row})",
                "Share of source values erwin accepted.")
    ws.cell(row=rate, column=2).number_format = "0.0%"
    ver = line("Verification rate",
               f"=IF(B{total_row}=0,0,B{verified_row}/B{total_row})",
               "Share of source values confirmed identical inside erwin.")
    ws.cell(row=ver, column=2).number_format = "0.0%"
    line("High severity exceptions", '=COUNTIF(Exceptions!$A:$A,"High")',
         "Listed on the Exceptions sheet.")
    if ctx["results"]:
        formula = (f'=IF(AND(B{total_row}>0,B{verified_row}=B{total_row}),"PASS",'
                   f'IF(B{applied_row}=0,"FAIL - NOTHING APPLIED",'
                   f'IF(OR(B{altered_row}>0,B{skipped_row}>0),"REVIEW REQUIRED","PASS")))')
        note = "PASS only when every source value was applied and read back identical."
    else:
        # No injection result to judge against - say so rather than reporting
        # a failure that was never actually attempted.
        formula = "NOT VERIFIED - NO INJECTION RESULTS"
        note = ("This report was built from source data alone. Re-run batch_run.py to "
                "produce a verified report.")
    verdict = line("Migration verdict", formula, note, bold_value=True)
    ws.cell(row=verdict, column=2).font = Font(name=FONT, size=11, bold=True, color="C00000")

    row = ws.max_row + 2
    ws.cell(row=row, column=1, value="Counts on this sheet are live formulas over the other "
                                     "three sheets, so they stay correct if rows are filtered "
                                     "or corrected during review.").font = Font(
        name=FONT, size=9, italic=True, color="595959")
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=3)


# ---------------------------------------------------------------------------
def build_report(model_name, manifest, schema, results, classification,
                 counts, entities, sap_model, erwin_out, outdir: Path) -> Path:
    recon_rows = build_reconciliation(manifest, results)

    wb = Workbook()
    # Default font for every unstyled cell - cheaper than styling 11k rows by hand.
    wb._named_styles["Normal"].font = Font(name=FONT, size=10)

    ws_summary = wb.active
    ws_summary.title = "Summary"
    ws_defs = wb.create_sheet("UDP Definition")
    ws_recon = wb.create_sheet("Value Reconciliation")
    ws_exc = wb.create_sheet("Exceptions")

    write_reconciliation(ws_recon, recon_rows)
    write_definitions(ws_defs, schema, results, recon_rows)
    write_exceptions(ws_exc, recon_rows, schema, results, classification, entities)

    signals = (classification or {}).get("signals", {}) or {}
    ctx = {
        "generated": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "model_name": model_name,
        "sap_model": sap_model or (classification or {}).get("model", "n/a"),
        "erwin_out": erwin_out or "n/a",
        "pd_version": (classification or {}).get("pd_version", "n/a"),
        "extraction_id": (classification or {}).get("extraction_id", "n/a"),
        "band": (classification or {}).get("band", "n/a"),
        "band_label": (classification or {}).get("band_label", "n/a"),
        "automation_range": " to ".join(
            f"{v}%" for v in (classification or {}).get("sow_automation_range", [])) or "n/a",
        "entities_source": signals.get("entities", (counts or {}).get("Entity", "n/a")),
        "attributes_source": signals.get("attributes",
                                         (counts or {}).get("EntityAttribute", "n/a")),
        "ext_properties": signals.get("extension_properties", "n/a"),
        "ext_values": signals.get("extension_values", "n/a"),
        "entities_target": (results or {}).get("entities_in_erwin", "Not recorded"),
        "results": results,
        "injection_state": "Yes" if results else "No - report built from source data only",
        "session_note": (results or {}).get("session", "Not recorded"),
        "recon_last_row": len(recon_rows) + 1,
    }
    write_summary(ws_summary, ctx)

    outdir.mkdir(parents=True, exist_ok=True)
    out_path = outdir / f"{model_name}_UDP_Migration_Report.xlsx"
    wb.save(out_path)
    return out_path


def main():
    ap = argparse.ArgumentParser(description="Generate the UDP migration Excel report.")
    ap.add_argument("--model_name", required=True)
    ap.add_argument("--manifest", required=True, type=Path)
    ap.add_argument("--schema", required=True, type=Path)
    ap.add_argument("--results", type=Path, help="injection_results.json from erwin_load.py")
    ap.add_argument("--classification", type=Path)
    ap.add_argument("--baseline", type=Path)
    ap.add_argument("--sap_model")
    ap.add_argument("--erwin_out")
    ap.add_argument("--outdir", required=True, type=Path)
    a = ap.parse_args()

    manifest = read_json(a.manifest, [])
    schema = read_json(a.schema, [])
    if not manifest and not schema:
        print("       ERROR: No manifest or schema data found - report not generated.")
        return 1

    results = read_json(a.results) if a.results else None
    classification = read_json(a.classification, {}) if a.classification else {}
    counts = read_json(a.baseline / "counts.json", {}) if a.baseline else {}
    entities = read_json(a.baseline / "entities.json", []) if a.baseline else []

    out_path = build_report(a.model_name, manifest, schema, results, classification,
                            counts, entities, a.sap_model, a.erwin_out, a.outdir)
    print(f"  -> Excel report saved to: {out_path.resolve()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
