name: SonarQube Scan

on:
  push:

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: sqa_75ed4cda2d4a1696ca29b1d5a5f6e8f5c30f2b90
          SONAR_HOST_URL: http://74.225.250.93:9000/
        with:
          args: >
            -Dsonar.projectKey=testing-sonar-repo
            -Dsonar.projectName=testing-sonar-repo
            -Dsonar.sources=.
            -Dsonar.exclusions=**/__pycache__/**,**/*.pyc,**/output_*/**,**/output_excel_reports/**,**/output_jsons/**,.pytest_cache/**
            -Dsonar.python.version=3.13
