name: SonarQube Scan

on:
  push:

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: sqp_018ff34b341cfee51d83e6a6bf23fa5bcf9dfb2f
          SONAR_HOST_URL: https://sesvc.shell.com/
        with:
          args: >
            -Dsonar.projectKey=com.shell.idso-oic-it4it-lineage-sub-system
            -Dsonar.projectName=idso-oic-it4it-lineage-sub-system
            -Dsonar.sources=.
            -Dsonar.exclusions=**/__pycache__/**,**/*.pyc,**/output_*/**,**/output_excel_reports/**,**/output_jsons/**,.pytest_cache/**
            -Dsonar.python.version=3.13
